#!/bin/bash

start_pl_path="$PWD/pack/plugins/start"
opt_pl_path="$PWD/pack/plugins/opt"

if [[ ! -d "$start_pl_path" && $(basename $PWD) == ".vim" ]]; then
    mkdir -p "$start_pl_path"
fi

if [[ ! -d "$opt_pl_path" && $(basename $PWD) == ".vim" ]]; then
    mkdir -p "$opt_pl_path"
fi

if [[ $? -eq 0 ]]; then
    cd "$start_pl_path"
    git clone git://github.com/ctrlpvim/ctrlp.vim.git
    git clone git://github.com/Raimondi/delimitMate.git
    git clone git://github.com/scrooloose/nerdtree.git
    git clone git://github.com/vim-airline/vim-airline.git
    # git clone git://github.com/vim-airline/vim-airline-themes.git
    git clone git://github.com/wakatime/vim-wakatime.git
    git clone git://github.com/tpope/vim-fugitive.git
    # git clone git://github.com/davidhalter/jedi-vim.git
    # if [[ $? -eq 0 ]]; then
    #     (cd "${start_pl_path}/jedi-vim" && git submodule update --init)
    # fi
    cd "$opt_pl_path"
    git clone git://github.com/mattn/emmet-vim.git
    git clone git://github.com/ap/vim-css-color.git
    git clone git://github.com/nvie/vim-flake8.git
fi
