#!/bin/bash

# Start plugins path
start_pl_path="$PWD/pack/plugins/start"
# Optional plugins path
opt_pl_path="$PWD/pack/plugins/opt"

# Start plugins
start_plugins=(
git@github.com:ctrlpvim/ctrlp.vim.git
git@github.com:Raimondi/delimitMate.git
git@github.com:scrooloose/nerdtree.git
git@github.com:vim-airline/vim-airline.git
git@github.com:tpope/vim-fugitive.git
git@github.com:prabirshrestha/vim-lsp.git
git@github.com:mattn/vim-lsp-settings.git
git@github.com:prabirshrestha/asyncomplete.vim.git
git@github.com:prabirshrestha/asyncomplete-lsp.vim.git
git@github.com:prabirshrestha/async.vim.git
)

# Optional plugins
opt_plugins=(
git@github.com:mattn/emmet-vim.git
git@github.com:ap/vim-css-color.git
git@github.com:nvie/vim-flake8.git
git@github.com:mgedmin/python-imports.vim.git
git@github.com:vim-python/python-syntax.git
git@github.com:pangloss/vim-javascript.git
# git@github.com:posva/vim-vue.git
git@github.com:leafOfTree/vim-vue-plugin.git
)


# Create plugins directory if does't exists
create_plugin_dir() {
    [[ ! -d "$start_pl_path" && $(basename $PWD) == ".vim" ]] && mkdir -p "$start_pl_path" || return 1
    [[ ! -d "$opt_pl_path" && $(basename $PWD) == ".vim" ]] && mkdir -p "$opt_pl_path" || return 1
}

if ! [[ -d "$start_pl_path" || -d "$opt_pl_path" ]]; then
    create_plugin_dir
fi

if [[ $? -eq 0 ]]; then
    cd "$start_pl_path"
    for plugin in "${start_plugins[@]}"; do
        pl_basename="${plugin##*/}"
        if [ ! -d "${pl_basename%.*}" ]; then
            git clone "$plugin"
        fi
    done
    cd "$opt_pl_path"
    for plugin in "${opt_plugins[@]}"; do
        pl_basename="${plugin##*/}"
        if [[ ! -d "${pl_basename%.*}" ]]; then
            git clone "$plugin"
        fi
    done
fi
